{
 "title": "David Lopez's Udacity SLI/SLO dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (rate(apiserver_request_total{job=\"apiserver\",code!~\"5..\"}[10m]))/sum (rate(apiserver_request_total{job=\"apiserver\"}[10m])) ) *100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90,sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\"}[1m])) by (le, verb))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error budget",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "1 - ((1 - (sum(increase(apiserver_request_total{job=\"apiserver\", code!~\"5..\"}[7d])) by (verb)) / sum(increase(apiserver_request_total{job=\"apiserver\"}[7d])) by (verb)) / (1 - 0.80))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"apiserver\",code=~\"2..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}